#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true 
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
#zhangyu
    filetree_direction = "left"
    guifont = "DejaVu Sans Mono for Powerline 16"
    enable_neomake = false
    enable_ale = false
#add myspacevim.vim at autoload
    bootstrap_before = "myspacevim#before"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

#zhangyu
[[layers]]
name = 'ctrlp'

[[layers]]
name = 'tags'

[[layers]]
name = 'cscope'
#cscope need add a createDB function
#~/.cache/vimfiles/repos/github.com/SpaceVim/cscope.vim/autoload/cscope.vim

#[[layers]]
#name = 'lang#c'
#enable_clang_syntax_highlight = true #need vim 8.0

[[layers]]
name = 'checkers'
enable = false

[[custom_plugins]]
   name = 'vim-scripts/Mark--Karkat'
   # note: you need to disable merged feature
   merged = false

